### ISSUE TITLE
Verboice `call finished` action has a wrong reflect

### ISSUE THREAD

**Issue by asterite** [instedd/hub#79]
The current reflect is (for example):

```
address: ...
var1:...
var2: ...
```

When it should be:

```
address: ...
vars:
  var1: ...
  var2: ...
```

because that's what Verboice sends in the notify call.
